### ISSUE TITLE
Not finding new images for CastleVille

### ISSUE THREAD

**Issue by kwinz1** [Mihc3/Settings#2]
The Image Downloader isn't working for CastleVille anymore. It doesn't detect any new images since 6/28/2012, although the game has added significant new content (and images) since then. Please help!

**Comment by Mihc3** [comment]
Images might be hidden in swf files. Use a flash decompiler to extract images from them.

**Comment by kwinz1** [comment]
Good suggestion, but it doesn't seem to be the case here.  I unchecked the "images only" checkbox and ran the downloader.  It took a long time to process, but it still found no new files to download.  No swf files and no new images.

**Comment by kwinz1** [comment]
I wonder if it might be due to a change that zynga made.  I notice in the frame source for a current castleville game that in addition to the "asset_url", there are now some "additional_asset_urls".  Here's a snippet -

"asset_url":"https:\/\/zynga1-a.akamaihd.net\/castles\/","snapiEnable":1,"images_url":"https:\/\/zynga1-a.akamaihd.net\/castles\/36985\/images\/","fb_app_id":"107040076067341","additional_asset_urls":"http:\/\/assets2.castle.zgncdn.com\/,http:\/\/assets3.castle.zgncdn.com\/,http:\/\/assets4.castle.zgncdn.com\/"

**Comment by Mihc3** [comment]
I just ran HashCaV.txt from http://mp-tools.tk, only 20% though, but without problems and I think it could make it to 100% with zero errors.
Download will only count as error if file does not exist on your computer after program tried to download it.

**Comment by kwinz1** [comment]
The errors were my fault, I realized, after I deleted and reinstalled I had forgotten to set it to the correct game.  It does run without errors now, and it's finding the newer files.  Sorry for the confusion, and thanks for your help.
